name: Build and Deploy to Google Cloud Run Production

on:
  push:
    branches:
      - main
    paths: 
      - 'server/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      APP: chatterbox
      REGION: asia-south1
      GAR_LOCATION: asia-south1
    steps:
      - name: "Checkout Server Code"
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
      - name: "Google Auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ secrets.PROJECT_ID }}"
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
      - name: "Build and push container"
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:production" ./server
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:production"
      - name: "Cloud Run Release"
        run : |-
          gcloud run services describe my-chat-server --region ${{ env.GAR_LOCATION }} --format export > service.yaml
          gcloud run services replace service.yaml
 